import {
  AppBar,
  IconButton,
  Toolbar,
  Typography,
} from "@material-ui/core";
import Head from "next/head";
import React, { FC, useState } from "react";
import NavigationDrawer from "./NavigationDrawer";
import useStyles from "./styles";
import MenuIcon from "@material-ui/icons/Menu";

const Header: FC = () => {
  const [drawerOpen, setDrawerOpen] = useState(false);
  const styles = useStyles();
  return (
    <>
      <Head>
        <title>Road to Warp</title>
        <meta
          name="description"
          content="Generated by create next app"
        />
        <link rel="icon" href="/Alcubierre.png" />
      </Head>

      <header className={styles.header}>
        <AppBar position="static" className={styles.appBar}>
          <Toolbar>
            <IconButton
              edge="start"
              color="inherit"
              aria-label="menu"
              onClick={() => setDrawerOpen(true)}
            >
              <MenuIcon />
            </IconButton>
            <Typography variant="h6">Road to Warp</Typography>
          </Toolbar>
          <NavigationDrawer
            open={drawerOpen}
            onClose={() => setDrawerOpen(false)}
          />
        </AppBar>
      </header>
    </>
  );
};

export default Header;
