import {
  BottomNavigation,
  Typography,
  BottomNavigationAction,
  AppBar,
  Toolbar,
  IconButton,
  Drawer,
  Button,
} from "@material-ui/core";
import Head from "next/head";
import useStyles from "./styles";
import GitHubIcon from "@material-ui/icons/GitHub";
import MenuBookIcon from "@material-ui/icons/MenuBook";
import SearchIcon from "@material-ui/icons/Search";
import TimelineIcon from "@material-ui/icons/Timeline";
import MenuIcon from "@material-ui/icons/Menu";
import HomeIcon from "@material-ui/icons/Home";

import { useState } from "react";

const HomePage = () => {
  const [drawerOpen, setDrawerOpen] = useState(false);
  const styles = useStyles();
  return (
    <div className={styles.container}>
      <Head>
        <title>Road to Warp</title>
        <meta
          name="description"
          content="Generated by create next app"
        />
        <link rel="icon" href="/Alcubierre.png" />
      </Head>

      <header className={styles.header}>
        <AppBar position="static" className={styles.appBar}>
          <Toolbar>
            <IconButton
              edge="start"
              color="inherit"
              aria-label="menu"
              onClick={() => setDrawerOpen(true)}
            >
              <MenuIcon />
            </IconButton>
            <Typography variant="h6">Road to Warp</Typography>
          </Toolbar>
          <Drawer
            className={styles.drawer}
            open={drawerOpen}
            onClose={() => setDrawerOpen(false)}
          >
            <Button
              className={styles.drawerButton}
              startIcon={<HomeIcon />}
            >
              Home
            </Button>
            <Button
              className={styles.drawerButton}
              startIcon={<SearchIcon />}
            >
              Research Center
            </Button>
            <Button
              className={styles.drawerButton}
              startIcon={<MenuBookIcon />}
            >
              Learning Portal
            </Button>
            <Button
              className={styles.drawerButton}
              startIcon={<TimelineIcon />}
            >
              Timeline
            </Button>
          </Drawer>
        </AppBar>
      </header>
      <main className={styles.main}>
        <Typography
          className={styles.title}
          variant="h5"
          component="h1"
        >
          The Road to Warp
        </Typography>
        <Typography className={styles.title} component="h6">
          A place to learn, research, and dream about space and our
          journey to faster than light travel
        </Typography>
        <img src="/Alcubierre.png" alt="" width="400" />
        {/* <BottomNavigation showLabels className={styles.bottomNav}>
          <BottomNavigationAction
            label="Learn"
            icon={<MenuBookIcon />}
          />
          <BottomNavigationAction
            label="Research"
            icon={<SearchIcon />}
          />
          <BottomNavigationAction
            label="Timeline"
            icon={<TimelineIcon />}
          />
        </BottomNavigation> */}
      </main>

      <footer className={styles.footer}>
        <a href="https://github.com/jedi91/road-to-warp">
          <GitHubIcon />
        </a>
      </footer>
    </div>
  );
};

export default HomePage;
