import { Typography } from "@material-ui/core";
import Head from "next/head";
import useStyles from "./styles";

const HomePage = () => {
  const styles = useStyles();
  return (
    <div className={styles.container}>
      <Head>
        <title>Road to Warp</title>
        <meta
          name="description"
          content="Generated by create next app"
        />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Typography
          className={styles.title}
          variant="h5"
          component="h1"
        >
          The Road to Warp
        </Typography>
        <Typography className={styles.title} component="h6">
          Our quest to explore the stars
        </Typography>
      </main>

      <footer className={styles.footer}></footer>
    </div>
  );
};

export default HomePage;
